name: Build on master push

on:
  push:
    branches:
      - master
      - test-build

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build electrs image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.8.9
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg VERSION=${{matrix.version}} \
          --tag electrs:${{matrix.version}} .
